Fix suspicious/wrong method call
The preview of the Android plugin for Gradle v3 enables linting in
Release builds which has discovered the following:

android/src/main/java/com/oney/WebRTCModule/WebRTCView.java:453: Error: Suspicious method call; should probably call "layout" rather than "onLayout" [WrongCall]
            onLayout(
            ~~~~~~~~

   Explanation for issues of type "WrongCall":
   Custom views typically need to call measure() on their children, not
   onMeasure. Ditto for onDraw, onLayout, etc.